"""可再分发的 SRD 入门目录。

目录数据与规则代码刻意分离，后续可以从 CC BY 4.0 来源生成完整数据集，
而不必让规则服务依赖原始文档格式。
"""

SRD_ATTRIBUTION = {
    "title": "Systems Reference Document 5.1",
    "publisher": "Wizards of the Coast LLC",
    "license": "Creative Commons Attribution 4.0 International",
    "url": "https://creativecommons.org/licenses/by/4.0/",
}

STARTER_ITEMS = [
    {"slug": "club", "name": "短棒", "name_en": "Club", "kind": "weapon",
     "weight_lb": 2.0, "price_gp": 10, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d4",
                "damage_type": "bludgeoning"}},
    {"slug": "dagger", "name": "匕首", "name_en": "Dagger", "kind": "weapon",
     "weight_lb": 1.0, "price_gp": 200, "stackable": False,
     "weapon": {"to_hit_ability": "DEX", "damage": "1d4",
                "damage_type": "piercing"}},
    {"slug": "longsword", "name": "长剑", "name_en": "Longsword", "kind": "weapon",
     "weight_lb": 3.0, "price_gp": 1500, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d8",
                "damage_type": "slashing"}},
    {"slug": "handaxe", "name": "手斧", "name_en": "Handaxe", "kind": "weapon",
     "weight_lb": 2.0, "price_gp": 500, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d6",
                "damage_type": "slashing"}},
    {"slug": "mace", "name": "钉头锤", "name_en": "Mace", "kind": "weapon",
     "weight_lb": 4.0, "price_gp": 500, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d6",
                "damage_type": "bludgeoning"}},
    {"slug": "quarterstaff", "name": "长棍", "name_en": "Quarterstaff", "kind": "weapon",
     "weight_lb": 4.0, "price_gp": 20, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d6",
                "damage_type": "bludgeoning"}},
    {"slug": "spear", "name": "长矛", "name_en": "Spear", "kind": "weapon",
     "weight_lb": 3.0, "price_gp": 100, "stackable": False,
     "weapon": {"to_hit_ability": "STR", "damage": "1d6",
                "damage_type": "piercing"}},
    {"slug": "shortbow", "name": "短弓", "name_en": "Shortbow", "kind": "weapon",
     "weight_lb": 2.0, "price_gp": 2500, "stackable": False,
     "weapon": {"to_hit_ability": "DEX", "damage": "1d6",
                "damage_type": "piercing"}},
    {"slug": "shield", "name": "盾牌", "name_en": "Shield", "kind": "armor",
     "weight_lb": 6.0, "price_gp": 1000, "stackable": False,
     "armor": {"ac_bonus": 2, "slot": "shield"}},
    {"slug": "leather-armor", "name": "皮甲", "name_en": "Leather Armor",
     "kind": "armor", "weight_lb": 10.0, "price_gp": 1000,
     "stackable": False, "armor": {"base_ac": 11, "dex_cap": None,
                                     "slot": "armor"}},
    {"slug": "chain-shirt", "name": "链甲衫", "name_en": "Chain Shirt", "kind": "armor",
     "weight_lb": 20.0, "price_gp": 5000, "stackable": False,
     "armor": {"base_ac": 13, "dex_cap": 2, "slot": "armor"}},
    {"slug": "chain-mail", "name": "链甲", "name_en": "Chain Mail", "kind": "armor",
     "weight_lb": 55.0, "price_gp": 7500, "stackable": False,
     "armor": {"base_ac": 16, "dex_cap": 0, "slot": "armor"}},
    {"slug": "healing-potion", "name": "治疗药水", "name_en": "Potion of Healing",
     "kind": "consumable", "weight_lb": 0.5, "price_gp": 5000,
     "stackable": True, "effect": {"heal": "2d4+2"}},
    {"slug": "rations", "name": "口粮（1天）", "name_en": "Rations (1 day)",
     "kind": "gear", "weight_lb": 2.0, "price_gp": 50, "stackable": True},
    {"slug": "rope-hempen", "name": "麻绳（50尺）", "name_en": "Hempen Rope (50 feet)",
     "kind": "gear", "weight_lb": 10.0, "price_gp": 100, "stackable": True},
    {"slug": "backpack", "name": "背包", "name_en": "Backpack", "kind": "gear",
     "weight_lb": 5.0, "price_gp": 200, "stackable": False},
    {"slug": "bedroll", "name": "睡袋", "name_en": "Bedroll", "kind": "gear",
     "weight_lb": 7.0, "price_gp": 100, "stackable": False},
    {"slug": "torch", "name": "火把", "name_en": "Torch", "kind": "gear",
     "weight_lb": 1.0, "price_gp": 1, "stackable": True},
    {"slug": "waterskin", "name": "水袋", "name_en": "Waterskin", "kind": "gear",
     "weight_lb": 5.0, "price_gp": 20, "stackable": False},
    {"slug": "tinderbox", "name": "火绒盒", "name_en": "Tinderbox", "kind": "gear",
     "weight_lb": 1.0, "price_gp": 50, "stackable": False},
]

STARTER_SPELLS = [
    {"slug": "fire-bolt", "name": "火焰箭", "name_en": "Fire Bolt",
     "level": 0, "school": "塑能", "ritual": False,
     "classes": ["sorcerer", "wizard"], "kind": "attack",
     "damage": "1d10", "damage_type": "fire",
     "description": "进行一次远程法术攻击。"},
    {"slug": "cure-wounds", "name": "疗伤术", "name_en": "Cure Wounds",
     "level": 1, "school": "塑能", "ritual": False,
     "classes": ["bard", "cleric", "druid", "paladin", "ranger"],
     "kind": "heal", "heal": "1d8", "slot_scaling": "1d8",
     "description": "触碰一个生物并恢复生命值。施法属性调整值由程序加入。"},
    {"slug": "magic-missile", "name": "魔法飞弹", "name_en": "Magic Missile",
     "level": 1, "school": "塑能", "ritual": False,
     "classes": ["sorcerer", "wizard"], "kind": "damage",
     "damage": "3d4+3", "damage_type": "force",
     "slot_scaling": "1d4+1", "description": "首版按单一目标结算全部飞弹。"},
    {"slug": "fireball", "name": "火球术", "name_en": "Fireball",
     "level": 3, "school": "塑能", "ritual": False,
     "classes": ["sorcerer", "wizard"], "kind": "save",
     "save_ability": "DEX", "save_result": "half",
     "damage": "8d6", "damage_type": "fire", "slot_scaling": "1d6",
     "description": "目标进行敏捷豁免，成功时伤害减半。首版逐目标调用。"},
]

# Canonical loadout entries used by the built-in character presets.
STARTER_ITEMS.extend([
    {"slug": slug, "name": name, "name_en": name, "kind": kind,
     "weight_lb": 1.0, "price_gp": 0, "stackable": stackable,
     **data}
    for slug, name, kind, stackable, data in [
        ("greataxe", "Greataxe", "weapon", False, {"weapon": {"to_hit_ability": "STR", "damage": "1d12", "damage_type": "slashing"}}),
        ("javelin", "Javelin", "weapon", True, {"weapon": {"to_hit_ability": "STR", "damage": "1d6", "damage_type": "piercing"}}),
        ("rapier", "Rapier", "weapon", False, {"weapon": {"to_hit_ability": "DEX", "damage": "1d8", "damage_type": "piercing"}}),
        ("scimitar", "Scimitar", "weapon", False, {"weapon": {"to_hit_ability": "DEX", "damage": "1d6", "damage_type": "slashing"}}),
        ("shortsword", "Shortsword", "weapon", False, {"weapon": {"to_hit_ability": "DEX", "damage": "1d6", "damage_type": "piercing"}}),
        ("longbow", "Longbow", "weapon", False, {"weapon": {"to_hit_ability": "DEX", "damage": "1d8", "damage_type": "piercing"}}),
        ("light-crossbow", "Light Crossbow", "weapon", False, {"weapon": {"to_hit_ability": "DEX", "damage": "1d8", "damage_type": "piercing"}}),
        ("arrow", "Arrow", "ammunition", True, {}), ("bolt", "Bolt", "ammunition", True, {}),
        ("scale-mail", "Scale Mail", "armor", False, {"armor": {"base_ac": 14, "dex_cap": 2, "slot": "armor"}}),
        ("lute", "Lute", "gear", False, {"equipment_slots": ["hands"]}),
        ("explorer-pack", "Explorer's Pack", "gear", False, {}),
        ("diplomat-pack", "Diplomat's Pack", "gear", False, {}),
        ("priest-pack", "Priest's Pack", "gear", False, {}),
        ("dungeoneer-pack", "Dungeoneer's Pack", "gear", False, {}),
        ("burglar-pack", "Burglar's Pack", "gear", False, {}),
        ("scholar-pack", "Scholar's Pack", "gear", False, {}),
        ("holy-symbol", "Holy Symbol", "gear", False, {}),
        ("druidic-focus", "Druidic Focus", "gear", False, {}),
        ("component-pouch", "Component Pouch", "gear", False, {}),
        ("thieves-tools", "Thieves' Tools", "gear", False, {}),
        ("spellbook", "Spellbook", "gear", False, {}),
    ]
])

STARTER_SPELLS.extend([
    {"slug": slug, "name": name, "name_en": name, "level": level,
     "school": "utility", "ritual": False, "classes": classes,
     "kind": "utility", "description": "SRD starter spell"}
    for slug, name, level, classes in [
        ("vicious-mockery", "Vicious Mockery", 0, ["bard"]), ("mage-hand", "Mage Hand", 0, ["bard", "sorcerer", "warlock", "wizard"]),
        ("guidance", "Guidance", 0, ["cleric", "druid"]), ("sacred-flame", "Sacred Flame", 0, ["cleric"]), ("spare-the-dying", "Spare the Dying", 0, ["cleric"]),
        ("druidcraft", "Druidcraft", 0, ["druid"]), ("produce-flame", "Produce Flame", 0, ["druid"]), ("light", "Light", 0, ["sorcerer", "wizard"]),
        ("prestidigitation", "Prestidigitation", 0, ["sorcerer"]), ("eldritch-blast", "Eldritch Blast", 0, ["warlock"]),
        ("healing-word", "Healing Word", 1, ["bard"]), ("dissonant-whispers", "Dissonant Whispers", 1, ["bard"]), ("faerie-fire", "Faerie Fire", 1, ["bard", "druid"]), ("thunderwave", "Thunderwave", 1, ["bard"]),
        ("bless", "Bless", 1, ["cleric"]), ("guiding-bolt", "Guiding Bolt", 1, ["cleric"]), ("entangle", "Entangle", 1, ["druid"]),
        ("shield", "Shield", 1, ["sorcerer", "wizard"]), ("armor-of-agathys", "Armor of Agathys", 1, ["warlock"]), ("hex", "Hex", 1, ["warlock"]),
        ("detect-magic", "Detect Magic", 1, ["wizard"]), ("find-familiar", "Find Familiar", 1, ["wizard"]), ("mage-armor", "Mage Armor", 1, ["wizard"]), ("sleep", "Sleep", 1, ["wizard"]),
    ]
])
